export const posterPriceMap = {
  A3: 99,
  A4: 89,
  "12x12": 89,
  A6: 79,
  A7: 69,
};

export const FRAMING_COST = 79;

export const posters = [
  {
    id: "101",
    image: "/posters/ps1.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "102",
    image: "/posters/ps2.jpg",
    alt: "img",
    category: ["desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "103",
    image: "/posters/ps3.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "104",
    image: "/posters/ps4.jpg",
    alt: "img",
    category: ["movie"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "105",
    image: "/posters/ps5.jpg",
    alt: "img",
    category: ["mythology", "desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "106",
    image: "/posters/ps6.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "107",
    image: "/posters/ps7.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "108",
    image: "/posters/ps8.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "109",
    image: "/posters/ps9.jpg",
    alt: "img",
    category: ["bengali"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "110",
    image: "/posters/ps10.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "111",
    image: "/posters/ps11.jpg",
    alt: "img",
    category: ["art"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "112",
    image: "/posters/ps12.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "113",
    image: "/posters/ps13.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "114",
    image: "/posters/ps14.jpg",
    alt: "img",
    category: ["bengali"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "115",
    image: "/posters/ps15.jpg",
    alt: "img",
    category: ["bengali"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "116",
    image: "/posters/ps16.jpg",
    alt: "img",
    category: ["desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "117",
    image: "/posters/ps17.jpg",
    alt: "img",
    category: ["bengali"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "118",
    image: "/posters/ps18.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "119",
    image: "/posters/ps19.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "120",
    image: "/posters/ps20.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "121",
    image: "/posters/ps21.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "122",
    image: "/posters/ps22.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "123",
    image: "/posters/ps23.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "124",
    image: "/posters/ps24.jpg",
    alt: "img",
    category: ["art"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "125",
    image: "/posters/ps25.jpg",
    alt: "img",
    category: ["desi", "quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "126",
    image: "/posters/ps26.jpg",
    alt: "img",
    category: ["abstract", "mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "127",
    image: "/posters/ps27.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "128",
    image: "/posters/ps28.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "129",
    image: "/posters/ps29.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "130",
    image: "/posters/ps30.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "131",
    image: "/posters/ps31.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "132",
    image: "/posters/ps32.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "133",
    image: "/posters/ps33.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "134",
    image: "/posters/ps34.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "135",
    image: "/posters/ps35.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "136",
    image: "/posters/ps36.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "137",
    image: "/posters/ps37.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "138",
    image: "/posters/ps38.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "139",
    image: "/posters/ps39.jpg",
    alt: "img",
    category: ["desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "140",
    image: "/posters/ps40.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "141",
    image: "/posters/ps41.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "142",
    image: "/posters/ps42.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "143",
    image: "/posters/ps43.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "144",
    image: "/posters/ps44.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "145",
    image: "/posters/ps45.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "146",
    image: "/posters/ps46.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "147",
    image: "/posters/ps47.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "148",
    image: "/posters/ps48.jpg",
    alt: "img",
    category: ["desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "149",
    image: "/posters/ps49.jpg",
    alt: "img",
    category: ["bengali"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "150",
    image: "/posters/ps50.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "151",
    image: "/posters/ps51.jpg",
    alt: "img",
    category: ["art"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "152",
    image: "/posters/ps52.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "153",
    image: "/posters/ps53.jpg",
    alt: "img",
    category: ["desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "154",
    image: "/posters/ps54.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "155",
    image: "/posters/ps55.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "156",
    image: "/posters/ps56.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "157",
    image: "/posters/ps57.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "158",
    image: "/posters/ps58.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "159",
    image: "/posters/ps59.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "160",
    image: "/posters/ps60.jpg",
    alt: "img",
    category: ["art"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "161",
    image: "/posters/ps61.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "162",
    image: "/posters/ps62.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "163",
    image: "/posters/ps63.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "164",
    image: "/posters/ps64.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "165",
    image: "/posters/ps65.jpg",
    alt: "img",
    category: ["abstract", "art"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "166",
    image: "/posters/ps66.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "167",
    image: "/posters/ps67.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "168",
    image: "/posters/ps68.jpg",
    alt: "img",
    category: ["art"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "169",
    image: "/posters/ps69.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "170",
    image: "/posters/ps70.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "171",
    image: "/posters/ps71.jpg",
    alt: "img",
    category: ["art"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "172",
    image: "/posters/ps72.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "173",
    image: "/posters/ps73.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "174",
    image: "/posters/ps74.jpg",
    alt: "img",
    category: ["abstract", "mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "175",
    image: "/posters/ps75.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "176",
    image: "/posters/ps76.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "177",
    image: "/posters/ps77.jpg",
    alt: "img",
    category: ["art"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "178",
    image: "/posters/ps78.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "179",
    image: "/posters/ps79.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "180",
    image: "/posters/ps80.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "181",
    image: "/posters/ps81.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "182",
    image: "/posters/ps82.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "183",
    image: "/posters/ps83.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "184",
    image: "/posters/ps84.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "185",
    image: "/posters/ps85.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "186",
    image: "/posters/ps86.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "187",
    image: "/posters/ps87.jpg",
    alt: "img",
    category: ["cinema", "desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "188",
    image: "/posters/ps88.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "189",
    image: "/posters/ps89.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "190",
    image: "/posters/ps90.jpg",
    alt: "img",
    category: ["quotes", "desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "191",
    image: "/posters/ps91.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "192",
    image: "/posters/ps92.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "193",
    image: "/posters/ps93.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "194",
    image: "/posters/ps94.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "195",
    image: "/posters/ps95.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "196",
    image: "/posters/ps96.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "197",
    image: "/posters/ps97.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "198",
    image: "/posters/ps98.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "199",
    image: "/posters/ps99.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "200",
    image: "/posters/ps100.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "201",
    image: "/posters/ps101.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "202",
    image: "/posters/ps102.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "203",
    image: "/posters/ps103.jpg",
    alt: "img",
    category: ["quotes", "desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "204",
    image: "/posters/ps104.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "205",
    image: "/posters/ps105.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "206",
    image: "/posters/ps106.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "207",
    image: "/posters/ps107.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "208",
    image: "/posters/ps108.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "209",
    image: "/posters/ps109.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "210",
    image: "/posters/ps110.jpg",
    alt: "img",
    category: ["quotes", "abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "211",
    image: "/posters/ps111.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "212",
    image: "/posters/ps112.jpg",
    alt: "img",
    category: ["quotes", "abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "213",
    image: "/posters/ps113.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "214",
    image: "/posters/ps114.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "215",
    image: "/posters/ps115.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "216",
    image: "/posters/ps116.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "217",
    image: "/posters/ps117.jpg",
    alt: "img",
    category: ["quotes", "abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "218",
    image: "/posters/ps118.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "219",
    image: "/posters/ps119.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "220",
    image: "/posters/ps120.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "221",
    image: "/posters/ps121.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "222",
    image: "/posters/ps122.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "223",
    image: "/posters/ps123.jpg",
    alt: "img",
    category: ["cinema"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "224",
    image: "/posters/ps124.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "225",
    image: "/posters/ps125.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "226",
    image: "/posters/ps126.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "227",
    image: "/posters/ps127.jpg",
    alt: "img",
    category: ["music", "desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "228",
    image: "/posters/ps128.jpg",
    alt: "img",
    category: ["music", "desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "229",
    image: "/posters/ps129.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "230",
    image: "/posters/ps130.jpg",
    alt: "img",
    category: ["quotes", "desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "231",
    image: "/posters/ps131.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "232",
    image: "/posters/ps132.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "233",
    image: "/posters/ps133.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "234",
    image: "/posters/ps134.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "235",
    image: "/posters/ps135.jpg",
    alt: "img",
    category: ["quotes", "music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "236",
    image: "/posters/ps136.jpg",
    alt: "img",
    category: ["desi"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "237",
    image: "/posters/ps137.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "238",
    image: "/posters/ps138.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "239",
    image: "/posters/ps139.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "240",
    image: "/posters/ps140.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "241",
    image: "/posters/ps141.jpg",
    alt: "img",
    category: ["abstract"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "242",
    image: "/posters/ps142.jpg",
    alt: "img",
    category: ["mythology"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "243",
    image: "/posters/ps143.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "244",
    image: "/posters/ps144.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "245",
    image: "/posters/ps145.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "246",
    image: "/posters/ps146.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "247",
    image: "/posters/ps147.jpg",
    alt: "img",
    category: ["quotes"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "248",
    image: "/posters/ps148.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "249",
    image: "/posters/ps149.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
  {
    id: "250",
    image: "/posters/ps150.jpg",
    alt: "img",
    category: ["music"],
    sizes: ["A3", "A4", "12x12", "A6", "A7"],
  },
];
